#!/usr/bin/env python3
"""
Three-Way Implementation Comparison
Compares Custom Python, FilterPy, and VHDL UKF implementations

This is the FINAL validation step - ensures all three implementations agree.
Any significant disagreement indicates a bug in one of the implementations.

Expected agreement:
- Custom Python vs FilterPy: RMSE < 0.01m (should be nearly identical)
- Custom Python vs VHDL: RMSE < 0.5m (Q24.24 quantization tolerable)
- FilterPy vs VHDL: RMSE < 0.5m (cross-validation)

Statistical tests:
- Pairwise RMSE
- Maximum deviation
- Correlation coefficients
- T-test for systematic bias
"""

import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "test_data" / "real_world"
PYTHON_CUSTOM_DIR = BASE_DIR / "results" / "python_outputs" / "custom"
PYTHON_FILTERPY_DIR = BASE_DIR / "results" / "python_outputs" / "filterpy"
VHDL_GHDL_DIR = BASE_DIR / "results" / "vhdl_outputs" / "ghdl"
VHDL_VIVADO_DIR = BASE_DIR / "results" / "vhdl_outputs" / "vivado"
MANUAL_DIR = BASE_DIR / "results" / "manual_inspection"
OUTPUT_DIR = BASE_DIR / "results" / "three_way_comparison"

Q_SCALE = 2**24

def load_ground_truth(dataset_name):
    """Load ground truth trajectory"""
    csv_file = DATA_DIR / f"{dataset_name}.csv"
    return pd.read_csv(csv_file)

def load_python_outputs(dataset_name, implementation='custom'):
    """Load Python UKF outputs"""
    if implementation == 'custom':
        output_dir = PYTHON_CUSTOM_DIR
        prefix = 'custom'
    else:
        output_dir = PYTHON_FILTERPY_DIR
        prefix = 'filterpy'
    
    pattern = f"{prefix}_{dataset_name.replace('.csv', '')}*.csv"
    matches = list(output_dir.glob(pattern))
    
    if not matches:
        return None
    
    return pd.read_csv(matches[0])

def load_vhdl_outputs(dataset_name, tool='ghdl'):
    """Load VHDL outputs (from manual inspection files)"""
    # Use human-readable comparison files generated by generate_human_readable_outputs.py
    csv_file = MANUAL_DIR / f"vhdl_readable_{dataset_name}.csv"
    
    if not csv_file.exists():
        return None
    
    # Extract VHDL estimates
    df = pd.read_csv(csv_file)
    
    vhdl_outputs = pd.DataFrame({
        'cycle': df['cycle'],
        'time': df['time'],
        'est_x_pos': df['vhdl_x_pos'],
        'est_y_pos': df['vhdl_y_pos'],
        'est_z_pos': df['vhdl_z_pos'],
        'est_x_vel': df.get('vhdl_x_vel', np.nan),
        'est_y_vel': df.get('vhdl_y_vel', np.nan),
        'est_z_vel': df.get('vhdl_z_vel', np.nan)
    })
    
    return vhdl_outputs

def compute_pairwise_rmse(est1, est2, state_name):
    """Compute RMSE between two implementations for a specific state"""
    if est1 is None or est2 is None:
        return np.nan
    
    # Align cycles
    min_len = min(len(est1), len(est2))
    
    diff = est1[state_name].values[:min_len] - est2[state_name].values[:min_len]
    rmse = np.sqrt(np.mean(diff**2))
    
    return rmse

def compute_correlation(est1, est2, state_name):
    """Compute correlation coefficient"""
    if est1 is None or est2 is None:
        return np.nan
    
    min_len = min(len(est1), len(est2))
    
    corr, _ = stats.pearsonr(
        est1[state_name].values[:min_len],
        est2[state_name].values[:min_len]
    )
    
    return corr

def perform_t_test(est1, est2, state_name):
    """Test for systematic bias between implementations"""
    if est1 is None or est2 is None:
        return np.nan, np.nan
    
    min_len = min(len(est1), len(est2))
    
    diff = est1[state_name].values[:min_len] - est2[state_name].values[:min_len]
    
    # One-sample t-test: is mean difference significantly different from 0?
    t_stat, p_value = stats.ttest_1samp(diff, 0)
    
    return t_stat, p_value

def compare_implementations(dataset_name):
    """Compare all three implementations for one dataset"""
    print(f"\n{'='*80}")
    print(f"Dataset: {dataset_name}")
    print('='*80)
    
    # Load all implementations
    ground_truth = load_ground_truth(dataset_name)
    custom_py = load_python_outputs(dataset_name, 'custom')
    filterpy = load_python_outputs(dataset_name, 'filterpy')
    vhdl = load_vhdl_outputs(dataset_name)
    
    # Check availability
    available = {}
    for name, impl in [('Custom Python', custom_py), ('FilterPy', filterpy), ('VHDL', vhdl)]:
        if impl is not None:
            available[name] = impl
            print(f"✓ {name}: {len(impl)} cycles")
        else:
            print(f"✗ {name}: Not available")
    
    if len(available) < 2:
        print("⚠ Need at least 2 implementations for comparison")
        return None
    
    # Pairwise comparisons
    results = []
    
    pairs = [
        ('Custom Python', 'FilterPy', 0.01),  # Should be nearly identical
        ('Custom Python', 'VHDL', 0.5),       # Q24.24 quantization
        ('FilterPy', 'VHDL', 0.5)             # Cross-validation
    ]
    
    for impl1_name, impl2_name, threshold in pairs:
        if impl1_name not in available or impl2_name not in available:
            continue
        
        impl1 = available[impl1_name]
        impl2 = available[impl2_name]
        
        print(f"\n{impl1_name} vs {impl2_name}:")
        
        # Position RMSE
        pos_x_rmse = compute_pairwise_rmse(impl1, impl2, 'est_x_pos')
        pos_y_rmse = compute_pairwise_rmse(impl1, impl2, 'est_y_pos')
        pos_z_rmse = compute_pairwise_rmse(impl1, impl2, 'est_z_pos')
        
        # 3D magnitude RMSE
        min_len = min(len(impl1), len(impl2))
        diff_3d = np.sqrt(
            (impl1['est_x_pos'].values[:min_len] - impl2['est_x_pos'].values[:min_len])**2 +
            (impl1['est_y_pos'].values[:min_len] - impl2['est_y_pos'].values[:min_len])**2 +
            (impl1['est_z_pos'].values[:min_len] - impl2['est_z_pos'].values[:min_len])**2
        )
        pos_mag_rmse = np.sqrt(np.mean(diff_3d**2))
        max_deviation = diff_3d.max()
        
        print(f"  Position RMSE:")
        print(f"    X:     {pos_x_rmse:.6f} m")
        print(f"    Y:     {pos_y_rmse:.6f} m")
        print(f"    Z:     {pos_z_rmse:.6f} m")
        print(f"    3D Mag: {pos_mag_rmse:.6f} m")
        print(f"  Max deviation: {max_deviation:.6f} m")
        
        # Correlation
        corr_x = compute_correlation(impl1, impl2, 'est_x_pos')
        print(f"  Correlation: {corr_x:.6f}")
        
        # T-test
        t_stat, p_value = perform_t_test(impl1, impl2, 'est_x_pos')
        print(f"  Systematic bias test: t={t_stat:.4f}, p={p_value:.4f}")
        
        # Assessment
        if pos_mag_rmse < threshold:
            print(f"  ✓ AGREEMENT EXCELLENT (RMSE < {threshold}m)")
            status = 'PASS'
        else:
            print(f"  ✗ AGREEMENT POOR (RMSE >= {threshold}m)")
            status = 'FAIL'
        
        # Store results
        results.append({
            'dataset': dataset_name,
            'implementation_1': impl1_name,
            'implementation_2': impl2_name,
            'threshold_m': threshold,
            'pos_x_rmse': pos_x_rmse,
            'pos_y_rmse': pos_y_rmse,
            'pos_z_rmse': pos_z_rmse,
            'pos_mag_rmse': pos_mag_rmse,
            'max_deviation': max_deviation,
            'correlation': corr_x,
            't_statistic': t_stat,
            'p_value': p_value,
            'status': status
        })
    
    return pd.DataFrame(results)

def plot_comparison(dataset_name, available_impls):
    """Plot side-by-side comparison of implementations"""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    # X position time series
    for name, impl in available_impls.items():
        axes[0, 0].plot(impl['time'], impl['est_x_pos'], label=name, alpha=0.7)
    
    axes[0, 0].set_xlabel('Time (s)')
    axes[0, 0].set_ylabel('X Position (m)')
    axes[0, 0].set_title(f'X Position - {dataset_name}')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)
    
    # Pairwise difference scatter (if 2+ implementations)
    if len(available_impls) >= 2:
        impl_list = list(available_impls.items())
        impl1_name, impl1 = impl_list[0]
        impl2_name, impl2 = impl_list[1]
        
        min_len = min(len(impl1), len(impl2))
        
        axes[0, 1].scatter(
            impl1['est_x_pos'].values[:min_len],
            impl2['est_x_pos'].values[:min_len],
            alpha=0.3, s=10
        )
        
        # Perfect agreement line
        min_val = min(impl1['est_x_pos'].min(), impl2['est_x_pos'].min())
        max_val = max(impl1['est_x_pos'].max(), impl2['est_x_pos'].max())
        axes[0, 1].plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2)
        
        axes[0, 1].set_xlabel(f'{impl1_name} X Position (m)')
        axes[0, 1].set_ylabel(f'{impl2_name} X Position (m)')
        axes[0, 1].set_title('Implementation Agreement')
        axes[0, 1].grid(True, alpha=0.3)
    
    # Difference time series
    if len(available_impls) >= 2:
        impl1_name, impl1 = impl_list[0]
        impl2_name, impl2 = impl_list[1]
        
        min_len = min(len(impl1), len(impl2))
        diff = impl1['est_x_pos'].values[:min_len] - impl2['est_x_pos'].values[:min_len]
        
        axes[1, 0].plot(impl1['time'].values[:min_len], diff, linewidth=1)
        axes[1, 0].axhline(y=0, color='r', linestyle='--', alpha=0.5)
        axes[1, 0].set_xlabel('Time (s)')
        axes[1, 0].set_ylabel('Difference (m)')
        axes[1, 0].set_title(f'{impl1_name} - {impl2_name}')
        axes[1, 0].grid(True, alpha=0.3)
    
    # Error distribution
    if len(available_impls) >= 2:
        axes[1, 1].hist(diff, bins=50, alpha=0.7, edgecolor='black')
        axes[1, 1].axvline(x=0, color='r', linestyle='--', linewidth=2)
        axes[1, 1].set_xlabel('Difference (m)')
        axes[1, 1].set_ylabel('Frequency')
        axes[1, 1].set_title('Difference Distribution')
        axes[1, 1].grid(True, alpha=0.3, axis='y')
    
    plt.tight_layout()
    
    plot_file = OUTPUT_DIR / f"comparison_{dataset_name}.png"
    plt.savefig(plot_file, dpi=150)
    plt.close()
    
    return plot_file

def main():
    print("="*80)
    print("THREE-WAY IMPLEMENTATION COMPARISON")
    print("="*80)
    print("Comparing:")
    print("  1. Custom Python UKF")
    print("  2. FilterPy UKF")
    print("  3. VHDL UKF (GHDL)")
    
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Find datasets
    datasets = sorted(DATA_DIR.glob("*.csv"))
    real_world = [d.stem for d in datasets if 'drone_euroc' in d.name or 'f1_' in d.name or 'synthetic' in d.name]
    
    if not real_world:
        print("\n✗ No datasets found")
        return
    
    print(f"\nFound {len(real_world)} datasets")
    
    all_results = []
    
    for dataset_name in real_world:
        try:
            results_df = compare_implementations(dataset_name)
            
            if results_df is not None:
                all_results.append(results_df)
                
                # Save per-dataset results
                csv_file = OUTPUT_DIR / f"comparison_{dataset_name}.csv"
                results_df.to_csv(csv_file, index=False, float_format='%.6f')
                print(f"\n✓ Results saved: {csv_file.name}")
        
        except Exception as e:
            print(f"\n✗ Error comparing {dataset_name}: {e}")
            import traceback
            traceback.print_exc()
    
    # Combined results
    if all_results:
        combined_df = pd.concat(all_results, ignore_index=True)
        
        csv_file = OUTPUT_DIR / "comparison_all_datasets.csv"
        combined_df.to_csv(csv_file, index=False, float_format='%.6f')
        
        print(f"\n{'='*80}")
        print("OVERALL COMPARISON SUMMARY")
        print('='*80)
        
        # Group by pair
        for (impl1, impl2), group in combined_df.groupby(['implementation_1', 'implementation_2']):
            print(f"\n{impl1} vs {impl2}:")
            print(f"  Average RMSE: {group['pos_mag_rmse'].mean():.6f} m")
            print(f"  Max RMSE: {group['pos_mag_rmse'].max():.6f} m")
            print(f"  Pass rate: {(group['status'] == 'PASS').sum()}/{len(group)}")
        
        print(f"\n✓ Combined results: {csv_file}")
    
    print(f"\n{'='*80}")
    print("THREE-WAY COMPARISON COMPLETE")
    print('='*80)
    print(f"Results: {OUTPUT_DIR}")

if __name__ == "__main__":
    main()
