#!/usr/bin/env python3
"""
Manual Comparison Tool
Generates detailed HTML reports for specific cycles

When you notice a suspicious cycle in the interactive viewer or Excel file,
use this tool to generate a comprehensive HTML report with:
- All 9 states side-by-side (VHDL vs Python vs GT)
- Absolute and percentage errors
- Covariance diagonal elements
- Measurement innovation
- Visual plots

Usage:
  python manual_comparison_tool.py --dataset drone_euroc_mh01 --cycle 247
  python manual_comparison_tool.py --dataset f1_monaco --cycles 100 150 200
"""

import numpy as np
import pandas as pd
from pathlib import Path
import argparse
import matplotlib.pyplot as plt
from jinja2 import Template

BASE_DIR = Path(__file__).parent.parent
MANUAL_DIR = BASE_DIR / "results" / "manual_inspection"
OUTPUT_DIR = BASE_DIR / "results" / "manual_inspection" / "cycle_reports"

# HTML template for cycle report
HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Cycle {{cycle}} Analysis - {{dataset}}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }
        h1 {
            color: #333;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
        }
        h2 {
            color: #555;
            margin-top: 30px;
            border-bottom: 2px solid #ddd;
            padding-bottom: 5px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
            background-color: white;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        th {
            background-color: #4CAF50;
            color: white;
            padding: 12px;
            text-align: left;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        .good {
            background-color: #c6efce !important;
        }
        .warning {
            background-color: #ffeb9c !important;
        }
        .bad {
            background-color: #ffc7ce !important;
        }
        .metric-box {
            display: inline-block;
            padding: 15px;
            margin: 10px;
            background-color: white;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .status-{{status_class}} {
            color: {{status_color}};
            font-weight: bold;
            font-size: 1.2em;
        }
        img {
            max-width: 100%;
            margin: 20px 0;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <h1>Cycle {{cycle}} Detailed Analysis</h1>
    <p><strong>Dataset:</strong> {{dataset}}</p>
    <p><strong>Time:</strong> {{time:.4f}} seconds</p>
    <p><strong>Status:</strong> <span class="status-{{status_class}}">{{status}}</span></p>
    
    <h2>Position State (meters)</h2>
    <table>
        <tr>
            <th>Axis</th>
            <th>Ground Truth</th>
            <th>VHDL Estimate</th>
            <th>Python Reference</th>
            <th>VHDL Error</th>
            <th>VHDL % Error</th>
            <th>VHDL vs Python</th>
        </tr>
        {{position_rows}}
    </table>
    
    <h2>Velocity State (m/s)</h2>
    <table>
        <tr>
            <th>Axis</th>
            <th>Ground Truth</th>
            <th>VHDL Estimate</th>
            <th>Python Reference</th>
            <th>VHDL Error</th>
        </tr>
        {{velocity_rows}}
    </table>
    
    <h2>Acceleration State (m/s²)</h2>
    <table>
        <tr>
            <th>Axis</th>
            <th>Ground Truth</th>
            <th>VHDL Estimate</th>
            <th>Python Reference</th>
            <th>VHDL Error</th>
        </tr>
        {{acceleration_rows}}
    </table>
    
    <h2>Summary Metrics</h2>
    <div>
        <div class="metric-box">
            <strong>3D Position Error:</strong><br>
            {{pos_mag_error:.4f}} m
        </div>
        <div class="metric-box">
            <strong>VHDL vs Python Diff:</strong><br>
            {{vhdl_py_diff:.4f}} m
        </div>
        <div class="metric-box">
            <strong>Max Axis Error:</strong><br>
            {{max_axis_error:.4f}} m ({{max_axis}})
        </div>
    </div>
    
    <h2>Error Visualization</h2>
    <img src="{{plot_filename}}" alt="Cycle {{cycle}} Visualization">
    
    <h2>Context</h2>
    <p>This cycle is at position {{cycle}}/{{total_cycles}} in the trajectory.</p>
    <p>Recommendation: {{recommendation}}</p>
    
    <hr>
    <p style="text-align: center; color: #888; font-size: 0.9em;">
        Generated by manual_comparison_tool.py
    </p>
</body>
</html>
"""

def load_comparison_data(dataset_name):
    """Load comparison CSV"""
    csv_file = MANUAL_DIR / f"vhdl_readable_{dataset_name}.csv"
    if not csv_file.exists():
        raise FileNotFoundError(
            f"Comparison data not found: {csv_file}\n"
            f"Run generate_human_readable_outputs.py first"
        )
    
    return pd.read_csv(csv_file)

def generate_table_row(axis, gt_val, vhdl_val, py_val, error, pct_error=None, vhdl_py_diff=None):
    """Generate HTML table row with color coding"""
    # Determine cell class based on error magnitude
    if abs(error) < 0.5:
        cell_class = 'good'
    elif abs(error) < 1.0:
        cell_class = 'warning'
    else:
        cell_class = 'bad'
    
    row = f"""
    <tr>
        <td><strong>{axis}</strong></td>
        <td>{gt_val:.6f}</td>
        <td>{vhdl_val:.6f}</td>
        <td>{py_val:.6f if not np.isnan(py_val) else 'N/A'}</td>
        <td class="{cell_class}">{error:.6f}</td>
    """
    
    if pct_error is not None:
        row += f'<td>{pct_error:.2f}%</td>'
    
    if vhdl_py_diff is not None:
        row += f'<td>{vhdl_py_diff:.6f}</td>'
    
    row += '</tr>'
    
    return row

def create_cycle_plot(data, cycle, dataset_name):
    """Create visualization plot for the cycle"""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    row = data.iloc[cycle]
    
    # 1. State comparison bar chart (position)
    states = ['X', 'Y', 'Z']
    gt_pos = [row['gt_x_pos'], row['gt_y_pos'], row['gt_z_pos']]
    vhdl_pos = [row['vhdl_x_pos'], row['vhdl_y_pos'], row['vhdl_z_pos']]
    
    x_pos = np.arange(len(states))
    width = 0.35
    
    axes[0, 0].bar(x_pos - width/2, gt_pos, width, label='Ground Truth', alpha=0.7)
    axes[0, 0].bar(x_pos + width/2, vhdl_pos, width, label='VHDL', alpha=0.7)
    axes[0, 0].set_xlabel('Axis')
    axes[0, 0].set_ylabel('Position (m)')
    axes[0, 0].set_title(f'Position State - Cycle {cycle}')
    axes[0, 0].set_xticks(x_pos)
    axes[0, 0].set_xticklabels(states)
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3, axis='y')
    
    # 2. Error breakdown
    errors = [row['err_x_pos'], row['err_y_pos'], row['err_z_pos']]
    colors = ['green' if abs(e) < 0.5 else 'yellow' if abs(e) < 1.0 else 'red' for e in errors]
    
    axes[0, 1].bar(states, [abs(e) for e in errors], color=colors, alpha=0.7)
    axes[0, 1].set_ylabel('Absolute Error (m)')
    axes[0, 1].set_title('Error Magnitude by Axis')
    axes[0, 1].grid(True, alpha=0.3, axis='y')
    
    # 3. Error context (window around cycle)
    window_start = max(0, cycle - 25)
    window_end = min(len(data), cycle + 25)
    window_data = data.iloc[window_start:window_end]
    
    axes[1, 0].plot(window_data['cycle'], window_data['err_pos_mag'], 'b-', linewidth=1, alpha=0.7)
    axes[1, 0].scatter([cycle], [row['err_pos_mag']], c='red', s=100, marker='o', zorder=5)
    axes[1, 0].axhline(y=0.5, color='green', linestyle='--', alpha=0.5, label='Excellent')
    axes[1, 0].axhline(y=1.0, color='yellow', linestyle='--', alpha=0.5, label='Acceptable')
    axes[1, 0].set_xlabel('Cycle')
    axes[1, 0].set_ylabel('Position Error (m)')
    axes[1, 0].set_title(f'Error Context (±25 cycles)')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)
    
    # 4. Velocity comparison
    gt_vel = [row['gt_x_vel'], row['gt_y_vel'], row['gt_z_vel']]
    vhdl_vel = [row.get('vhdl_x_vel', np.nan), row.get('vhdl_y_vel', np.nan), row.get('vhdl_z_vel', np.nan)]
    
    axes[1, 1].bar(x_pos - width/2, gt_vel, width, label='Ground Truth', alpha=0.7)
    axes[1, 1].bar(x_pos + width/2, vhdl_vel, width, label='VHDL', alpha=0.7)
    axes[1, 1].set_xlabel('Axis')
    axes[1, 1].set_ylabel('Velocity (m/s)')
    axes[1, 1].set_title(f'Velocity State - Cycle {cycle}')
    axes[1, 1].set_xticks(x_pos)
    axes[1, 1].set_xticklabels(states)
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3, axis='y')
    
    plt.tight_layout()
    
    plot_filename = f"cycle{cycle:04d}_plot.png"
    plot_path = OUTPUT_DIR / plot_filename
    plt.savefig(plot_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    return plot_filename

def generate_cycle_report(data, cycle, dataset_name):
    """Generate detailed HTML report for one cycle"""
    print(f"\nGenerating report for cycle {cycle}...")
    
    row = data.iloc[cycle]
    
    # Position rows
    position_rows = ""
    for axis in ['x', 'y', 'z']:
        gt = row[f'gt_{axis}_pos']
        vhdl = row[f'vhdl_{axis}_pos']
        py = row.get(f'py_{axis}_pos', np.nan)
        error = row[f'err_{axis}_pos']
        pct_error = (abs(error) / abs(gt) * 100) if abs(gt) > 0.001 else 0
        vhdl_py_diff = row.get(f'diff_vhdl_py_{axis}', np.nan)
        
        position_rows += generate_table_row(
            axis.upper(), gt, vhdl, py, error, pct_error, vhdl_py_diff
        )
    
    # Velocity rows
    velocity_rows = ""
    for axis in ['x', 'y', 'z']:
        gt = row[f'gt_{axis}_vel']
        vhdl = row.get(f'vhdl_{axis}_vel', np.nan)
        py = row.get(f'py_{axis}_vel', np.nan) if 'py_x_vel' in data.columns else np.nan
        error = vhdl - gt if not np.isnan(vhdl) else np.nan
        
        velocity_rows += generate_table_row(axis.upper(), gt, vhdl, py, error)
    
    # Acceleration rows (similar pattern)
    acceleration_rows = ""
    for axis in ['x', 'y', 'z']:
        gt = row[f'gt_{axis}_acc']
        vhdl = np.nan  # Usually not in VHDL output
        py = np.nan
        error = np.nan
        
        acceleration_rows += generate_table_row(axis.upper(), gt, vhdl, py, error)
    
    # Create plot
    plot_filename = create_cycle_plot(data, cycle, dataset_name)
    
    # Determine status
    pos_mag_error = row['err_pos_mag']
    if pos_mag_error < 0.5:
        status = "✓ EXCELLENT"
        status_class = "good"
        status_color = "green"
        recommendation = "This cycle shows excellent VHDL accuracy. No action needed."
    elif pos_mag_error < 1.0:
        status = "⚠ ACCEPTABLE"
        status_class = "warning"
        status_color = "orange"
        recommendation = "Errors are within acceptable bounds but higher than ideal. Monitor for trends."
    else:
        status = "✗ INVESTIGATE"
        status_class = "bad"
        status_color = "red"
        recommendation = "Error exceeds 1.0m threshold. Investigate VHDL simulation logs, check for numerical issues, verify Q24.24 conversion."
    
    # Find max axis error
    errors_dict = {
        'X': abs(row['err_x_pos']),
        'Y': abs(row['err_y_pos']),
        'Z': abs(row['err_z_pos'])
    }
    max_axis = max(errors_dict, key=errors_dict.get)
    max_axis_error = errors_dict[max_axis]
    
    # Render template
    template = Template(HTML_TEMPLATE)
    html_content = template.render(
        cycle=cycle,
        dataset=dataset_name,
        time=row['time'],
        status=status,
        status_class=status_class,
        status_color=status_color,
        position_rows=position_rows,
        velocity_rows=velocity_rows,
        acceleration_rows=acceleration_rows,
        pos_mag_error=pos_mag_error,
        vhdl_py_diff=row.get('diff_vhdl_py_mag', np.nan),
        max_axis=max_axis,
        max_axis_error=max_axis_error,
        plot_filename=plot_filename,
        total_cycles=len(data),
        recommendation=recommendation
    )
    
    # Save HTML
    html_filename = OUTPUT_DIR / f"cycle{cycle:04d}_report.html"
    with open(html_filename, 'w') as f:
        f.write(html_content)
    
    print(f"  ✓ HTML report: {html_filename.name}")
    print(f"  ✓ Plot: {plot_filename}")
    print(f"  Status: {status}")
    
    return html_filename

def main():
    parser = argparse.ArgumentParser(description='Manual Cycle Comparison Tool')
    parser.add_argument('--dataset', type=str, required=True,
                        help='Dataset name (e.g., drone_euroc_mh01)')
    parser.add_argument('--cycle', type=int, help='Single cycle to analyze')
    parser.add_argument('--cycles', type=int, nargs='+', help='Multiple cycles to analyze')
    args = parser.parse_args()
    
    print("="*80)
    print("MANUAL CYCLE COMPARISON TOOL")
    print("="*80)
    print(f"Dataset: {args.dataset}")
    
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Load data
    data = load_comparison_data(args.dataset)
    print(f"Loaded {len(data)} cycles")
    
    # Determine which cycles to analyze
    if args.cycle is not None:
        cycles = [args.cycle]
    elif args.cycles is not None:
        cycles = args.cycles
    else:
        # Default: analyze cycles with errors > 1.0m
        problematic = data[data['err_pos_mag'] >= 1.0]
        if len(problematic) == 0:
            print("\n✓ No problematic cycles found (all errors < 1.0m)")
            print("Analyzing top 3 cycles with highest errors instead:")
            cycles = data.nlargest(3, 'err_pos_mag')['cycle'].tolist()
        else:
            cycles = problematic['cycle'].tolist()[:5]  # Max 5
        
        print(f"\nAuto-selected {len(cycles)} cycles for analysis:")
        print(f"  Cycles: {cycles}")
    
    # Generate reports
    for cycle in cycles:
        if cycle >= len(data):
            print(f"\n✗ Cycle {cycle} out of range (max: {len(data)-1})")
            continue
        
        try:
            html_file = generate_cycle_report(data, cycle, args.dataset)
        except Exception as e:
            print(f"\n✗ Error generating report for cycle {cycle}: {e}")
            import traceback
            traceback.print_exc()
    
    print(f"\n{'='*80}")
    print("REPORTS GENERATED")
    print('='*80)
    print(f"Output directory: {OUTPUT_DIR}")
    print("\nOpen the HTML files in your browser for detailed analysis.")

if __name__ == "__main__":
    main()
