set_part xczu7ev-ffvc1156-2-e
set_property target_language VHDL [current_project]

read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/shared/sqrt_cordic.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/shared/sin_cos_cordic.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/shared/matrix_inverse_3x3.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/cholesky_7x7.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/sigma_7d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/predicti_bicycle.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/process_noise_bicycle.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/predicted_mean_7d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/predicted_covariance_7d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/innovation_covariance_7d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/cross_covariance_7d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/kalman_gain_7d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/bicycle_ukf/state_update_7d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/cholesky_multiplier_array.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/cholesky_col2_parallel.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/cholesky_col3_parallel.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/cholesky_col4_parallel.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/cholesky_col5_parallel.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/cholesky_col678_parallel.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/cholsky_9.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/sigma_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/predicti_ca3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/process_noise_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/predicted_mean_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/covariance_reconstruct_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/innovation_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/innovation_covariance_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/measurement_mean_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/cross_covariance_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/kalman_gain_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/state_update_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ca_ukf/prediction_phase_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ctra_ukf/predicti_ctra.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/ctra_ukf/process_noise_ctra.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/singer_ukf/singer_exp_cordic.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/singer_ukf/predicti_singer3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/singer_ukf/singer_process_noise_singer_p_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/singer_ukf/prediction_phase_p_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/exp_lut.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/log_lut.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/imm_likelihood.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/imm_prob_update.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/state_mapper_9d_to_7d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/state_mapper_9d_to_7d_ctra.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/state_mapper_7d_to_9d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/imm_friend_state_mixer.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/imm_friend_covariance_mixer.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/imm_output_fusion.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/prediction_phase_p_3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/predicti_singer3d.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/ca_measurement_update_imm.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/singer_measurement_update_imm.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/singer_ukf_supreme_imm.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/bicycle_ukf_supreme_imm.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/ctra_ukf_supreme_imm.vhd"
read_vhdl -vhdl2008 "/home/arunupscee/Desktop/xtortion/collection/imm_friend/src/imm/imm_friend_top.vhd"

synth_design -top imm_friend_top -part xczu7ev-ffvc1156-2-e -mode out_of_context

set rpt_dir "/home/arunupscee/Desktop/xtortion/collection/reports/imm_friend"
file mkdir $rpt_dir
report_utilization -file "$rpt_dir/utilization.rpt" -hierarchical
report_timing_summary -file "$rpt_dir/timing_summary.rpt" -max_paths 10
report_power -file "$rpt_dir/power.rpt"
puts "IMM Friend synthesis complete. Reports in $rpt_dir"
